/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'MyApp.view.LoginIncorrect',
        'MyApp.view.LoginCorrect',
        'MyApp.view.LoginBestPractice'
    ],

    autoShow: true,
    height: 300,
    width: 400,
    layout: {
        type: 'accordion'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'loginincorrect'
                },
                {
                    xtype: 'logincorrect'
                },
                {
                    xtype: 'loginbestpractice'
                }
            ]
        });

        me.callParent(arguments);
    }

});