/*
 * File: app/controller/Login.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Login', {
    extend: 'Ext.app.Controller',

    onButtonClickIncorrect: function(button, e, eOpts) {
        var formPanel = button.up('form'),
            user = formPanel.down('textfield#user').getValue(),
            pass = formPanel.down('textfield#pass').getValue();

        Ext.Ajax.request({
            url: 'php/login.php',
            params: {
                user: user,
                password: pass
            },
            success: function(conn, response, options, eOpts) {

                Ext.Msg.show({
                    title:'Info',
                    msg: 'Login feito com sucesso',
                    icon: Ext.Msg.INFO,
                    buttons: Ext.Msg.OK
                });
            },
            failure: function(conn, response, options, eOpts) {

                Ext.Msg.show({
                    title:'Erro',
                    msg: 'Usuário ou Senha incorretos.',
                    icon: Ext.Msg.ERROR,
                    buttons: Ext.Msg.OK
                });
            }
        });
    },

    onButtonClickCorrect: function(button, e, eOpts) {
        var formPanel = button.up('form'),
            user = formPanel.down('textfield#user').getValue(),
            pass = formPanel.down('textfield#pass').getValue();

        Ext.Ajax.request({
            url: 'php/login.php',
            params: {
                user: user,
                password: pass
            },
            success: function(conn, response, options, eOpts) {

                var result = Ext.JSON.decode(conn.responseText, true);

                if (!result){ // caso seja null
                    result = {};
                    result.success = false;
                    result.msg = conn.responseText;
                }

                if (result.success) {

                    Ext.Msg.show({
                        title:'Info',
                        msg: result.msg,
                        icon: Ext.Msg.INFO,
                        buttons: Ext.Msg.OK
                    });

                } else {

                    Ext.Msg.show({
                        title:'Erro',
                        msg: result.msg,
                        icon: Ext.Msg.ERROR,
                        buttons: Ext.Msg.OK
                    });
                }
            },
            failure: function(conn, response, options, eOpts) {

                Ext.Msg.show({
                    title:'Erro - Contate Administrador do sistema!',
                    msg: conn.responseText,
                    icon: Ext.Msg.ERROR,
                    buttons: Ext.Msg.OK
                });
            }
        });
    },

    onButtonClickBestPractice: function(button, e, eOpts) {
        var formPanel = button.up('form'),
            user = formPanel.down('textfield#user').getValue(),
            pass = formPanel.down('textfield#pass').getValue();

        Ext.Ajax.request({
            url: 'php/login.php',
            params: {
                user: user,
                password: pass
            },
            scope: this,
            success: this.onLoginSucess,
            failure: this.onLoginFailure
        });
    },

    showMessage: function(title, msg, icon) {
        Ext.Msg.show({
            title: title,
            msg: msg,
            icon: icon,
            buttons: Ext.Msg.OK
        });
    },

    onLoginSucess: function(conn, response, options, eOpts) {
        var result = Ext.JSON.decode(conn.responseText, true);

        console.log(result);

        if (!result){ // caso seja null
            result = {};
            result.success = false;
            result.msg = conn.responseText;
        }

        if (result.success) {

            this.showMessage('Info', result.msg, Ext.Msg.INFO);

        } else {

            this.showMessage('Erro', result.msg, Ext.Msg.ERROR);

        }
    },

    onLoginFailure: function(conn, response, options, eOpts) {
        this.showMessage('Erro - Contate Administrador do sistema!', conn.responseText, Ext.Msg.ERROR);
    },

    init: function(application) {
        this.control({
            "loginincorrect button#submit": {
                click: this.onButtonClickIncorrect
            },
            "logincorrect button#submit": {
                click: this.onButtonClickCorrect
            },
            "loginbestpractice button#submit": {
                click: this.onButtonClickBestPractice
            }
        });
    }

});
